##Spring Configuration
server:
  port: 7800
spring:
  application:
    name: report-ms
  devtools:
    add-properties: false
  data:
    mongodb:
      uri: mongodb://admin:secret123@localhost:27017/webflux_db?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-ms-group
      auto-offset-reset: earliest
  profiles:
    include:

kafka:
  topics:
    bootcamp-report-sync: bootcamp.report.sync
